# Generated by Django 4.1.7 on 2023-11-26 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0006_patient_receptionist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientrecord',
            name='patient',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.patientrecord'),
        ),
    ]
