# Generated by Django 4.1.7 on 2023-11-26 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_remove_patientrecord_patient_patient_patient_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='receptionist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospitals.receptionist'),
        ),
    ]
